# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Scrape kings league website

on:
  workflow_dispatch: 
    
  repository_dispatch:
    types:
      - webhook
      
  schedule: 
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: 
          node scraping/leaderboard.js
          git config user.name ghostmaker92
          git config user.email dryor.19@gmail.com
          git add * 
          git commmit -m "[bot] Update Kings League Database"
          git push origin main
